COMMON: &common
  SECRET_KEY: insecure
    
DEVELOPMENT: &development
  <<: *common
  STRIPE_SECRET:"sk_07vkIYtFhTJY68s2pipRKmlvDtiqk"
  STRIPE_PUBLISHABLE:"pk_07vkx4yqszys5bnTNnHPSAAimkCie"
  MONGODB_DB:"resupply_dev"
  DEBUG: True
  
STAGING: &staging
  <<: *common
  STRIPE_SECRET:"sk_07vkIYtFhTJY68s2pipRKmlvDtiqk"
  STRIPE_PUBLISHABLE:"pk_07vkx4yqszys5bnTNnHPSAAimkCie"
  MONGODB_DB:"resupply_staging"
  SECRET_KEY: sortasecure
  
PRODUCTION: &production
  <<: *common
  STRIPE_SECRET:"sk_07vkIYtFhTJY68s2pipRKmlvDtiqk"
  STRIPE_PUBLISHABLE:"pk_07vkx4yqszys5bnTNnHPSAAimkCie"
  MONGODB_DB:"resupply_production"
  SECRET_KEY: p0c0n0$CyrusSirahImran
    
